// <auto-generated />
using System;
using HealthcareSystem.Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HealthcareSystem.Backend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Account", b =>
                {
                    b.Property<int>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AccountId"));

                    b.Property<string>("InsuranceUserID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AccountId");

                    b.HasIndex("InsuranceUserID")
                        .IsUnique()
                        .HasFilter("[InsuranceUserID] IS NOT NULL");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("HealthRecord", b =>
                {
                    b.Property<int>("RecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RecordId"));

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RecordId");

                    b.HasIndex("UserID");

                    b.ToTable("HealthRecords");
                });

            modelBuilder.Entity("HealthcareSystem.Backend.Models.Entity.CustomerInquiry", b =>
                {
                    b.Property<int>("InquiryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InquiryID"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateAnwser")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateQuestion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Questioner")
                        .HasColumnType("int");

                    b.Property<int>("Respondent")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("InquiryID");

                    b.HasIndex("AccountId");

                    b.ToTable("CustomerInquiries");
                });

            modelBuilder.Entity("HealthcareSystem.Backend.Models.Entity.CustomerRequest", b =>
                {
                    b.Property<int>("RequestID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RequestID"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateAccept")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateRequest")
                        .HasColumnType("datetime2");

                    b.Property<int>("PackageId")
                        .HasColumnType("int");

                    b.Property<int>("PaymentId")
                        .HasColumnType("int");

                    b.Property<string>("Periodic")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<int>("StaffId")
                        .HasColumnType("int");

                    b.HasKey("RequestID");

                    b.HasIndex("AccountId");

                    b.HasIndex("PackageId");

                    b.HasIndex("PaymentId")
                        .IsUnique();

                    b.HasIndex("StaffId");

                    b.ToTable("CustomerRequests");
                });

            modelBuilder.Entity("HealthcareSystem.Backend.Models.Entity.InsuranceDetail", b =>
                {
                    b.Property<int>("PackageID")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<int>("InsureID")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<DateTime>("DateEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateStart")
                        .HasColumnType("datetime2");

                    b.Property<int>("InsuranceID")
                        .HasColumnType("int");

                    b.HasKey("PackageID", "InsureID");

                    b.HasIndex("InsuranceID");

                    b.ToTable("InsuranceDetails");
                });

            modelBuilder.Entity("HealthcareSystem.Backend.Models.Entity.InsurancePolicy", b =>
                {
                    b.Property<int>("PolicyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PolicyID"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("MaxRefund")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("PayoutPercentage")
                        .HasColumnType("float");

                    b.HasKey("PolicyID");

                    b.ToTable("InsurancePolicy");
                });

            modelBuilder.Entity("HealthcareSystem.Backend.Models.Entity.PackageDetail", b =>
                {
                    b.Property<int>("PolicyID")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<int>("PackageID")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<DateTime>("DateEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateStart")
                        .HasColumnType("datetime2");

                    b.HasKey("PolicyID", "PackageID");

                    b.HasIndex("PackageID");

                    b.ToTable("PackageDetails");
                });

            modelBuilder.Entity("HealthcareSystem.Backend.Models.Entity.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("RequestId")
                        .HasColumnType("int");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("PaymentId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("HealthcareSystem.Backend.Models.Entity.PolicyPackage", b =>
                {
                    b.Property<int>("Packageid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Packageid"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Packageid");

                    b.ToTable("PolicyPackages");
                });

            modelBuilder.Entity("HealthcareSystem.Backend.Models.Entity.RefundDetail", b =>
                {
                    b.Property<int>("RefundDetailID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RefundDetailID"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PolicyId")
                        .HasColumnType("int");

                    b.Property<double>("RefundFee")
                        .HasColumnType("float");

                    b.Property<int>("RefundID")
                        .HasColumnType("int");

                    b.HasKey("RefundDetailID");

                    b.HasIndex("PolicyId");

                    b.HasIndex("RefundID");

                    b.ToTable("RefundDetails");
                });

            modelBuilder.Entity("HealthcareSystem.Backend.Models.Entity.RefundRequest", b =>
                {
                    b.Property<int>("RefundID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RefundID"));

                    b.Property<DateTime>("DateRefund")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateSend")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoptitalDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoptitalName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InsureId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("TotalRefundFee")
                        .HasColumnType("float");

                    b.HasKey("RefundID");

                    b.HasIndex("InsureId");

                    b.ToTable("RefundRequests");
                });

            modelBuilder.Entity("HealthcareSystem.Backend.Models.Entity.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Birthdate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CCCD")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fullname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Insurance", b =>
                {
                    b.Property<int>("InsuranceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InsuranceID"));

                    b.Property<string>("CardOpenDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegisterPlace")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("InsuranceID");

                    b.ToTable("Insurances");
                });

            modelBuilder.Entity("Account", b =>
                {
                    b.HasOne("Insurance", "Insurance")
                        .WithOne("Account")
                        .HasForeignKey("Account", "InsuranceUserID")
                        .HasPrincipalKey("Insurance", "UserID");

                    b.HasOne("HealthcareSystem.Backend.Models.Entity.User", "User")
                        .WithOne("Account")
                        .HasForeignKey("Account", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Insurance");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HealthRecord", b =>
                {
                    b.HasOne("Account", "Account")
                        .WithMany("HealthRecords")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("HealthcareSystem.Backend.Models.Entity.CustomerInquiry", b =>
                {
                    b.HasOne("Account", "Account")
                        .WithMany("CustomerInquiries")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("HealthcareSystem.Backend.Models.Entity.CustomerRequest", b =>
                {
                    b.HasOne("Account", "Account")
                        .WithMany("CustomerRequests")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HealthcareSystem.Backend.Models.Entity.PolicyPackage", "PolicyPackage")
                        .WithMany("CustomerRequests")
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HealthcareSystem.Backend.Models.Entity.Payment", "Payment")
                        .WithOne("CustomerRequest")
                        .HasForeignKey("HealthcareSystem.Backend.Models.Entity.CustomerRequest", "PaymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Account", "Staff")
                        .WithMany("ApproverRequests")
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Payment");

                    b.Navigation("PolicyPackage");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("HealthcareSystem.Backend.Models.Entity.InsuranceDetail", b =>
                {
                    b.HasOne("Insurance", "Insurance")
                        .WithMany("InsuranceDetails")
                        .HasForeignKey("InsuranceID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HealthcareSystem.Backend.Models.Entity.PolicyPackage", "PolicyPackage")
                        .WithMany("InsuranceDetails")
                        .HasForeignKey("PackageID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Insurance");

                    b.Navigation("PolicyPackage");
                });

            modelBuilder.Entity("HealthcareSystem.Backend.Models.Entity.PackageDetail", b =>
                {
                    b.HasOne("HealthcareSystem.Backend.Models.Entity.PolicyPackage", "PolicyPackage")
                        .WithMany("PackageDetails")
                        .HasForeignKey("PackageID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HealthcareSystem.Backend.Models.Entity.InsurancePolicy", "InsurancePolicy")
                        .WithMany("PackageDetails")
                        .HasForeignKey("PolicyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InsurancePolicy");

                    b.Navigation("PolicyPackage");
                });

            modelBuilder.Entity("HealthcareSystem.Backend.Models.Entity.RefundDetail", b =>
                {
                    b.HasOne("HealthcareSystem.Backend.Models.Entity.InsurancePolicy", "InsurancePolicy")
                        .WithMany("RefundDetails")
                        .HasForeignKey("PolicyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HealthcareSystem.Backend.Models.Entity.RefundRequest", "RefundRequest")
                        .WithMany("RefundDetails")
                        .HasForeignKey("RefundID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InsurancePolicy");

                    b.Navigation("RefundRequest");
                });

            modelBuilder.Entity("HealthcareSystem.Backend.Models.Entity.RefundRequest", b =>
                {
                    b.HasOne("Insurance", "Insurance")
                        .WithMany("RefundRequests")
                        .HasForeignKey("InsureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Insurance");
                });

            modelBuilder.Entity("Account", b =>
                {
                    b.Navigation("ApproverRequests");

                    b.Navigation("CustomerInquiries");

                    b.Navigation("CustomerRequests");

                    b.Navigation("HealthRecords");
                });

            modelBuilder.Entity("HealthcareSystem.Backend.Models.Entity.InsurancePolicy", b =>
                {
                    b.Navigation("PackageDetails");

                    b.Navigation("RefundDetails");
                });

            modelBuilder.Entity("HealthcareSystem.Backend.Models.Entity.Payment", b =>
                {
                    b.Navigation("CustomerRequest")
                        .IsRequired();
                });

            modelBuilder.Entity("HealthcareSystem.Backend.Models.Entity.PolicyPackage", b =>
                {
                    b.Navigation("CustomerRequests");

                    b.Navigation("InsuranceDetails");

                    b.Navigation("PackageDetails");
                });

            modelBuilder.Entity("HealthcareSystem.Backend.Models.Entity.RefundRequest", b =>
                {
                    b.Navigation("RefundDetails");
                });

            modelBuilder.Entity("HealthcareSystem.Backend.Models.Entity.User", b =>
                {
                    b.Navigation("Account")
                        .IsRequired();
                });

            modelBuilder.Entity("Insurance", b =>
                {
                    b.Navigation("Account")
                        .IsRequired();

                    b.Navigation("InsuranceDetails");

                    b.Navigation("RefundRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
